### PR TITLE
CBL-4345: cblite serve to allow multiple collections.

### PR DESCRIPTION
**Pull request by jianminzhao**
Also moved submodule, couchbase-lite-core, to release/master.

### CODE REVIEW

**Comment by jianminzhao** [comment]
Because of [CBL-4721](https://issues.couchbase.com/browse/CBL-4721), I cannot merge until the resolution of CBL-4721 lands in release/master branch of lite-core.

**Review by borrrden — COMMENTED** [review]
I don't understand what is going on here.  There are some fixes for some things that have recently broken but in what way is the goal of the ticket accomplished?  The only change I see to the serve command is that a log domain gets changed, and the mkcoll command allows multiple collections to be specified.

**Comment by jianminzhao** [comment]
The change in cblite is not big, most changes are in the core. Originally I put the the change in cblite/release/3.1 which is linked lite-core/release/3.1 and give the performance team the hash that they said they would build their program with out source. Now that the code in lite-core/release/3.1 has been available in release/master, so that I can port the feature to cblite/master and the official tool will have the new feature.

**Comment by jianminzhao** [comment]
Basically, I ported the relevant commit from cblite/release/3.1 to cblite/master and links lite-core to release/master.

**Comment by jianminzhao** [comment]
Because of a problem in lite-core, [CBL-4721](https://issues.couchbase.com/browse/CBL-4721), I cannot merge this PR to master until the fix of 4721 shows up in release/master, right?

**Comment by borrrden** [comment]
If it stops the build from succeeding then yes.

**Review by borrrden — APPROVED** [review]

**Pull request merged**
